[package]
name = "beans-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.32"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
simple-home-dir = "0.3.4"

[dependencies.tokio]
version = "1.37.0"
features = [
    "macros",
    "rt-multi-thread"
]

[dependencies.reqwest]
version = "0.12.4"
features = [
    "multipart",
    "stream",
    "json"
]