# .github/workflows/release.yml

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Github Release Tag'
        required: true

jobs:
  release:
    name: release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            filename: 'beans-rs'
          - os: windows-latest
            filename: 'beans-rs.exe'
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ matrix.filename }}
          tag_name: ${{ github.event.inputs.tag }}
          draft: false
          prerelease: true