# .github/workflows/release.yml

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Github Release Tag'
        required: true

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            filename: 'beans-rs'
          - os: windows-latest
            filename: 'beans-rs.exe'
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          EXTRA_FILES: "README.md LICENSE.txt"
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ matrix.filename }}
          tag_name: ${{ github.event.inputs.tag }}
          draft: false
          prerelease: true